### ISSUE TITLE
Integration test for htpasswd wasn't migrated

### ISSUE THREAD

**Issue by zoredache** [ansible-collections/community.general#56] opened 2020-03-26 23:56 UTC
##### SUMMARY

The module htpasswd ansible-collections/community.general
 was migrated to the communities.general collection.  But the associated integration tests seems to still be in the ansible/ansible repo.

- https://github.com/ansible-collections/community.general/blob/master/plugins/modules/web_infrastructure/htpasswd.pyhttps://github.com/ansible/ansible/blob/devel/test/support/integration/plugins/modules/htpasswd.py

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
htpasswd

**Comment by felixfontein** [comment] 2020-03-27 06:46
If you look closely, you can see that the file included in ansible/ansible is not an integration test for the htpasswd module, but another copy of the htpasswd module itself. And if you read the [README](https://github.com/ansible/ansible/tree/devel/test/support) file for the `test/support` directory in ansible/ansible, you'll also know why it is there. So it's not a bug at all :)

BTW, the htpasswd module has no integration tests (and never had some).

**Comment by zoredache** [comment] 2020-03-27 07:47
Ah, my mistake then.  Maybe I’ll try to add a PR with some then.  I was thinking about taking a stab at adding support for bcrypt, and configurable rounds.  Before changing anything I was trying to find the tests.

**Comment by felixfontein** [comment] 2020-03-27 08:18
Having integration (or unit) tests for that module would definitely be awesome!

**Comment by gundalow** [comment] 2020-03-27 13:28
@zoredache I appreciate that you were looking for tests before starting the changing functionality of htpasswd.

Feel free to raise a PR (even if it's Work in Progress) then we can help.

I guess we can close this issue for the moment.

**Closed by gundalow** 2020-03-27 13:28 UTC
